### ISSUE TITLE
项目后端无法跑起来啊，请大佬解决，已经star

### ISSUE THREAD

**Issue by arraycto** [Selegant/etl-admin#4]
1.kettle的包无法下载，后来pom添加后仍没解决
如下：
`	<repositories>
		<repository>
			<id>pentaho-repo</id>
			<url>http://repository.pentaho.org/artifactory/repo/</url>
		</repository>
	</repositories>`

2.无法下载datax相关的包

3，注释datax，依然错误，项目错误如下：类似这中，无法打包，无法拍起来，期待大佬解决。
F:\ideaproject\etl-admin-gitee\kettle\src\main\java\com\selegant\kettle\init\KettleInit.java:5:27
java: 程序包org.pentaho.di.core不存在

**Comment by Selegant** [comment]
http://selegant.synology.me:34567/share/settings-kettle.xml
这个是kettle的maven setting文件 
datax这个版本还未集成 可以先注释掉

**Comment by Selegant** [comment]
> 1.kettle的包无法下载，后来pom添加后仍没解决
> 如下：
> ` <repositories> <repository> <id>pentaho-repo</id> <url>http://repository.pentaho.org/artifactory/repo/</url> </repository> </repositories>`
> 
> 2.无法下载datax相关的包
> 
> 3，注释datax，依然错误，项目错误如下：类似这中，无法打包，无法拍起来，期待大佬解决。
> F:\ideaproject\etl-admin-gitee\kettle\src\main\java\com\selegant\kettle\init\KettleInit.java:5:27
> java: 程序包org.pentaho.di.core不存在

http://selegant.synology.me:34567/share/settings-kettle.xml
这个是kettle的maven setting文件
datax这个版本还未集成 可以先注释掉

**Comment by arraycto** [comment]
已经跑通。
